//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationalAreas
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationalAreas
    {
        public short idOperationalArea { get; set; }
        public string CodeOperationalArea { get; set; }
        public string DescOperationalArea { get; set; }
    }
}
