//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormSpaceShipTypes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filiation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filiation()
        {
            this.SpaceShipTypes = new HashSet<SpaceShipType>();
        }
    
        public int idFiliation { get; set; }
        public string CodeFiliation { get; set; }
        public string DescFiliations { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpaceShipType> SpaceShipTypes { get; set; }
    }
}
