//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormSpaceShipTypes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpaceShipEntitie : DbContext
    {
        public SpaceShipEntitie()
            : base("name=SpaceShipEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Filiation> Filiations { get; set; }
        public virtual DbSet<SpaceShipCategory> SpaceShipCategories { get; set; }
        public virtual DbSet<SpaceShipType> SpaceShipTypes { get; set; }
    }
}
